# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67ad2fd8173bd18a8a0de5071a3b31c72611bf09dd4d5bf5a42b1a78d5530362117c9e84b82133220bd3f384b011692d6e9eaee441a29cf3b7ce7a2a617f6802

test:
  secret_key_base: 519c56f7486b117ed15f0e39530fab4334732d7f2a62576c343b12266886c19e78b6689922668ce22ec8bbb951d5762840d6fccf0942ec063226732d21c8a394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
